import { MedicalPhrase, GestureKey } from "@/types";

const P = (key: GestureKey, label: string, swahili: string, english: string): MedicalPhrase => ({
  key, label, swahili, english,
});

export const MEDICAL_PHRASES: Record<GestureKey, MedicalPhrase> = {
  pain:       P("pain",       "Pain",        "Mgonjwa ana maumivu",          "The patient is in pain"),
  fever:      P("fever",      "Fever",       "Mgonjwa ana homa",             "The patient has a fever"),
  medicine:   P("medicine",   "Medicine",    "Nahitaji dawa",                "I need medicine"),
  emergency:  P("emergency",  "Emergency",   "Dharura! Nahitaji msaada haraka","Emergency! I need immediate help"),
  allergy:    P("allergy",    "Allergy",     "Nina mzio",                    "I have an allergy"),
  headache:   P("headache",   "Headache",    "Ninaumwa kichwa",              "I have a headache"),
  stomach:    P("stomach",    "Stomach",     "Ninaumwa tumbo",               "I have stomach pain"),
  diabetes:   P("diabetes",   "Diabetes",    "Nina ugonjwa wa kisukari",     "I have diabetes"),
  pregnancy:  P("pregnancy",  "Pregnancy",   "Nina mimba",                   "I am pregnant"),
  help:       P("help",       "Help",        "Tafadhali nisaidie",           "Please help me"),
  thirsty:    P("thirsty",    "Thirsty",     "Nina kiu",                     "I am thirsty"),
  thank_you:  P("thank_you",  "Thank You",   "Asante sana",                  "Thank you very much"),
  happy:      P("happy",      "Happy",       "Nina furaha",                  "I am happy"),
  sad:        P("sad",        "Sad",         "Nina huzuni",                  "I am sad"),
  hungry:     P("hungry",     "Hungry",      "Nina njaa",                    "I am hungry"),
  tired:      P("tired",      "Tired",       "Nimechoka",                    "I am tired"),
  sleep:      P("sleep",      "Sleep",       "Nahitaji kulala",              "I need to sleep"),
  water:      P("water",      "Water",       "Nahitaji maji",                "I need water"),
  food:       P("food",       "Food",        "Nahitaji chakula",             "I need food"),
  doctor:     P("doctor",     "Doctor",      "Nahitaji daktari",             "I need a doctor"),
  nurse:      P("nurse",      "Nurse",       "Nahitaji muuguzi",             "I need a nurse"),
  hospital:   P("hospital",   "Hospital",    "Nipeleke hospitali",           "Take me to the hospital"),
  sick:       P("sick",       "Sick",        "Ninajisikia mgonjwa",          "I feel sick"),
  cold:       P("cold",       "Cold",        "Nasikia baridi",               "I feel cold"),
  hot:        P("hot",        "Hot",         "Nasikia joto",                 "I feel hot"),
  dizzy:      P("dizzy",      "Dizzy",       "Nina kizunguzungu",            "I feel dizzy"),
  vomit:      P("vomit",      "Vomit",       "Ninatapika",                   "I am vomiting"),
  blood:      P("blood",      "Bleeding",    "Ninatoka damu",                "I am bleeding"),
  breathe:    P("breathe",    "Breathing",   "Nashindwa kupumua",            "I cannot breathe"),
  cough:      P("cough",      "Cough",       "Nina kikohozi",                "I have a cough"),
  sneeze:     P("sneeze",     "Sneeze",      "Ninapiga chafya",              "I am sneezing"),
  injection:  P("injection",  "Injection",   "Nahitaji sindano",             "I need an injection"),
  bandage:    P("bandage",    "Bandage",     "Nahitaji bandeji",             "I need a bandage"),
  wheelchair: P("wheelchair", "Wheelchair",  "Nahitaji kiti cha magurudumu", "I need a wheelchair"),
  ambulance:  P("ambulance",  "Ambulance",   "Piga gari la wagonjwa",        "Call an ambulance"),
  surgery:    P("surgery",    "Surgery",     "Nahitaji upasuaji",            "I need surgery"),
  xray:       P("xray",       "X-Ray",       "Nahitaji eksirei",             "I need an X-ray"),
  pressure:   P("pressure",   "Pressure",    "Nina shinikizo la damu",       "I have high blood pressure"),
  heart:      P("heart",      "Heart",       "Ninaumwa moyo",                "My heart hurts"),
  eye:        P("eye",        "Eye",         "Ninaumwa jicho",               "My eye hurts"),
  ear:        P("ear",        "Ear",         "Ninaumwa sikio",               "My ear hurts"),
  nose:       P("nose",       "Nose",        "Ninaumwa pua",                 "My nose hurts"),
  mouth:      P("mouth",      "Mouth",       "Ninaumwa mdomo",               "My mouth hurts"),
  hand:       P("hand",       "Hand",        "Ninaumwa mkono",               "My hand hurts"),
  leg:        P("leg",        "Leg",         "Ninaumwa mguu",                "My leg hurts"),
  back:       P("back",       "Back",        "Ninaumwa mgongo",              "My back hurts"),
  yes:        P("yes",        "Yes",         "Ndiyo",                        "Yes"),
  no:         P("no",         "No",          "Hapana",                       "No"),
  hello:      P("hello",      "Hello",       "Habari",                       "Hello"),
  goodbye:    P("goodbye",    "Goodbye",     "Kwaheri",                      "Goodbye"),
  please:     P("please",     "Please",      "Tafadhali",                    "Please"),
  sorry:      P("sorry",      "Sorry",       "Samahani",                     "Sorry"),
  wait:       P("wait",       "Wait",        "Subiri kidogo",                "Please wait"),
  stop:       P("stop",       "Stop",        "Acha",                         "Stop"),
};

export const PHRASES_LIST = Object.values(MEDICAL_PHRASES);
